name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  ci:
    name: Build & Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: sugarmanz/auto-native-setup-action@v0.0.4
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
          
#       - name: Lint
#         run: bash ./gradlew lint
        
#       - name: Unit tests
#         run: bash ./gradlew test --stacktrace

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Shipit
        run: auto shipit --dry-run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
