name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Auto
        uses: sugarmanz/auto-native-setup-action@v0.0.4
        
      - name: Shipit
        run: bash auto shipit --dry-run
